// <auto-generated />
using System;
using MediApp.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediApp.Api.Persistence.Migrations
{
    [DbContext(typeof(MediAppDbContext))]
    [Migration("20260506172434_ModeloCompleto")]
    partial class ModeloCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediApp.Api.Persistence.Entities.Lectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EvidenciaFotoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("evidencia_foto_hash");

                    b.Property<string>("EvidenciaFotoRuta")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("evidencia_foto_ruta");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdMedidor")
                        .HasColumnType("integer")
                        .HasColumnName("id_medidor");

                    b.Property<int>("IdOperario")
                        .HasColumnType("integer")
                        .HasColumnName("id_operario");

                    b.Property<decimal>("LecturaActual")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("lectura_actual");

                    b.Property<decimal>("LecturaAnterior")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("lectura_anterior");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("char(6)")
                        .HasColumnName("periodo");

                    b.Property<DateTimeOffset>("TimestampCaptura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_captura");

                    b.HasKey("Id")
                        .HasName("pk_lecturas");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasDatabaseName("ix_lecturas_id_cliente");

                    b.HasIndex("IdMedidor")
                        .HasDatabaseName("ix_lecturas_id_medidor");

                    b.ToTable("lecturas", (string)null);
                });

            modelBuilder.Entity("MediApp.Api.Persistence.Entities.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CargoBasico")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cargo_basico");

                    b.Property<decimal>("CargoExcedente")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cargo_excedente");

                    b.Property<decimal>("CargoFijo")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cargo_fijo");

                    b.Property<decimal>("ConsumoM3")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("consumo_m3");

                    b.Property<decimal>("Contribucion")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("contribucion");

                    b.Property<short>("Estrato")
                        .HasColumnType("smallint")
                        .HasColumnName("estrato");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdLectura")
                        .HasColumnType("integer")
                        .HasColumnName("id_lectura");

                    b.Property<decimal>("Subsidio")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subsidio");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_liquidaciones");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasDatabaseName("ix_liquidaciones_id_cliente");

                    b.HasIndex("IdLectura")
                        .IsUnique()
                        .HasDatabaseName("ix_liquidaciones_id_lectura");

                    b.ToTable("liquidaciones", (string)null);
                });

            modelBuilder.Entity("MediApp.Api.Persistence.Entities.Medidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaInstalacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_instalacion");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdSuscriptor")
                        .HasColumnType("integer")
                        .HasColumnName("id_suscriptor");

                    b.HasKey("Id")
                        .HasName("pk_medidores");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_medidores_codigo");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasDatabaseName("ix_medidores_id_cliente");

                    b.HasIndex("IdSuscriptor")
                        .HasDatabaseName("ix_medidores_id_suscriptor");

                    b.ToTable("medidores", (string)null);
                });

            modelBuilder.Entity("MediApp.Api.Persistence.Entities.Suscriptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("documento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<short>("Estrato")
                        .HasColumnType("smallint")
                        .HasColumnName("estrato");

                    b.Property<DateTimeOffset>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_suscriptores");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_suscriptores_documento");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasDatabaseName("ix_suscriptores_id_cliente");

                    b.ToTable("suscriptores", (string)null);
                });

            modelBuilder.Entity("MediApp.Api.Persistence.Entities.SyncRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FechaSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_sync");

                    b.Property<string>("HashServer")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_server");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEntidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_entidad");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_sync_registros");

                    b.HasIndex("IdCliente", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_registros_id_cliente_tipo");

                    b.HasIndex("Tipo", "IdEntidad")
                        .HasDatabaseName("ix_sync_registros_tipo_id_entidad");

                    b.ToTable("sync_registros", (string)null);
                });

            modelBuilder.Entity("MediApp.Api.Persistence.Entities.Lectura", b =>
                {
                    b.HasOne("MediApp.Api.Persistence.Entities.Medidor", "Medidor")
                        .WithMany()
                        .HasForeignKey("IdMedidor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lecturas_medidores_id_medidor");

                    b.Navigation("Medidor");
                });

            modelBuilder.Entity("MediApp.Api.Persistence.Entities.Liquidacion", b =>
                {
                    b.HasOne("MediApp.Api.Persistence.Entities.Lectura", "Lectura")
                        .WithMany()
                        .HasForeignKey("IdLectura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_liquidaciones_lecturas_id_lectura");

                    b.Navigation("Lectura");
                });

            modelBuilder.Entity("MediApp.Api.Persistence.Entities.Medidor", b =>
                {
                    b.HasOne("MediApp.Api.Persistence.Entities.Suscriptor", "Suscriptor")
                        .WithMany()
                        .HasForeignKey("IdSuscriptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medidores_suscriptores_id_suscriptor");

                    b.Navigation("Suscriptor");
                });
#pragma warning restore 612, 618
        }
    }
}
